#!/bin/bash
while true; do 
if ping -c 1 -W 5 google.com; then     
  echo -en '\E[47;32m'"\033[1mS\033[0m" 
echo "Connected!" 
else 
  echo -en '\E[47;31m'"\033[1mZ\033[0m" 
echo "Not Connected!" 
fi 

  sleep 5
  clear 
  sleep 1 
done