#!/bin/bash
while true; do 
if ping -c 1 -W 5 google.com; then
  echo -en '\E[47;32m'"\033[1mS\033[0m" 
  echo "Connected!" 
else 
  echo -en '\E[47;31m'"\033[1mZ\033[0m" 
  echo "Not Connected!"
  sleep 30
    if ping -c 1 -W 5 google.com; then
      gnome-terminal -e "/media/daavvis/'Seagate Bac'/opengapps/download_sources.sh [--shallow] [arm]"
    else echo "Waiting for connection.."
    fi
fi
  sleep 10
  clear
  sleep 1 
done
